// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: carts.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createCart = `-- name: CreateCart :one
INSERT INTO carts
(ID, user_id)
VALUES($1, $2)
RETURNING id, user_id
`

type CreateCartParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) CreateCart(ctx context.Context, arg CreateCartParams) (Cart, error) {
	row := q.db.QueryRowContext(ctx, createCart, arg.ID, arg.UserID)
	var i Cart
	err := row.Scan(&i.ID, &i.UserID)
	return i, err
}
