// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"github.com/google/uuid"
)

type Category struct {
	Name string
}

type Product struct {
	ID          uuid.UUID
	Sku         string
	Name        string
	Description string
	Price       float32
	Stockqty    int32
	Category    string
}

type User struct {
	ID        uuid.UUID
	FirstName string
	LastName  string
	Email     string
	PhoneNo   string
	Address   string
	Password  string
	Role      string
}
