// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: order_items.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (
  ID, quantity, price_at_purchase,
  order_id, product_id)
VALUES(
  $1, $2, $3,
  $4, $5)
RETURNING id, quantity, price_at_purchase, order_id, product_id
`

type CreateOrderItemParams struct {
	ID              uuid.UUID
	Quantity        int32
	PriceAtPurchase float32
	OrderID         uuid.UUID
	ProductID       uuid.UUID
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRowContext(ctx, createOrderItem,
		arg.ID,
		arg.Quantity,
		arg.PriceAtPurchase,
		arg.OrderID,
		arg.ProductID,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.Quantity,
		&i.PriceAtPurchase,
		&i.OrderID,
		&i.ProductID,
	)
	return i, err
}
